#!/bin/sh
#
## symrlink - create a symbolic link using the $SYSSYMA functionality
#

USAGE="Usage: `basename $0` filename"
OPTS="&JOBNAME.-&LYYMMDD.-&LHHMMSS."


if [ $# -eq 0 ]; then
    echo $USAGE >&2
    exit 1
fi

# Check if it's absolute or relative

if [ "${1#/}" = $1 ]; then
        # It' a relative link. so we work from pwd
        file=`pwd`/$1
else
        file=$1
fi


# If file exists we will move it to <file>.old

if [ -f $file ]; then
        echo "File exists. Moving to $1.old"
        mv $file $file.old
fi

# create the ls command arguments

dsign="$"
target="${dsign}SYSSYMA$file-$OPTS"
source=$file

command="ln -s $target $source"
`$command`
echo "Done. Any writes to $1 will result in a file $1$OPTS"
